LOCAL_PATH := $(call my-dir)/..

include $(CLEAR_VARS)

LOCAL_SRC_FILES := sqlite3.c

LOCAL_MODULE := sqlite3

LOCAL_CFLAGS := -DSQLITE_ENABLE_FTS4 -D_FILE_OFFSET_BITS=32 -DSQLITE_ENABLE_JSON1 -DSQLITE_DEFAULT_PAGE_SIZE=16384 -DSQLITE_MAX_DEFAULT_PAGE_SIZE=16384


ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
  LOCAL_LDFLAGS += "-Wl,-z,max-page-size=16384"
	LOCAL_LDFLAGS += "-Wl,-z,common-page-size=16384" 
endif

include $(BUILD_SHARED_LIBRARY)
